kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.13
    environment:
      GOOS: linux
      GOARCH: amd64
      GO111MODULE: 'on'
      CGO_ENABLED: 1
    commands:
    - go test ./...
    - go build -ldflags "-extldflags \"-static\"" -o waiter

  - name: publish
    image: plugins/docker
    settings:
      repo: mlclmj/waiter
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
