kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: mlclmj/waiter
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
